version: '2'
services:
  pgbouncer:
    build: .
    image: camptocamp/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - pgbouncer_certificate:/etc/pgbouncer/ssl
      - ./etc/pgbouncer:/etc/pgbouncer:ro
    restart: always
volumes: 
  pgbouncer_certificate:
