version: '2'
services:
  pgbouncer:
    build: .
    image: camptocamp/pgbouncer
    ports:
      - "6432:6432"
    volumes:
      - pgbouncer_certificate:/etc/pgbouncer/ssl
      - ./etc/pgbouncer:/etc/pgbouncer:ro
    restart: always
    environment: 
      USERLIST: "user md54d45974e13472b5a0be3533de4666414"
      PG_HBA: "hostssl all all 0.0.0.0/0 md5" 
      DB_MAPPING: "* = host=db"
      CERTIFICATE_DESCRIPTION: "/C=FR/O=camptocamp"
      EXTRA_CONFIG: "ignore_startup_parameters = extra_float_digits"
volumes: 
  pgbouncer_certificate:
